# packages_and_sources.R

library(car)
library(cluster)
library(cowplot)
library(cplm)
library(data.table)
library(doParallel)
library(dplyr)
library(factoextra)
library(foreach)
library(ggplot2)
library(ggrepel)
library(grid)
library(gridExtra)
library(Hmisc)
library(kableExtra)
library(KEGGREST)
library(knitr)
library(magrittr)
library(MASS)
library(parallel)
library(phyloseq)
library(stringr)
library(tibble)
library(vegan)
source("Aux_scripts/mgsub.R")
source("Aux_scripts/colorblind_pals.R")
